# Generated by Django 3.1.12 on 2021-08-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_title', models.CharField(blank=True, default=1, max_length=250, null=True)),
                ('photo', models.ImageField(upload_to='photos/about_us/%y/%m/%d')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'AboutUs',
                'verbose_name_plural': 'AboutUs',
            },
        ),
        migrations.CreateModel(
            name='BeforeAndAfter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='photos/before_and_after/%y/%m/%d')),
                ('feature', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'BeforeAndAfter',
                'verbose_name_plural': 'BeforeAndAfter',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, default='https://www.facebook.com/', max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, default='https://www.instagram.com', max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, default='https://www.instagram.com', max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, default='https://twitter.com/', max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('first_phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('second_phone_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='photos/logo/%y/%m/%d')),
                ('blog', models.CharField(max_length=250)),
                ('text_image', models.ImageField(blank=True, null=True, upload_to='photos/home/%y/%m/%d')),
                ('type_question', models.CharField(blank=True, max_length=250, null=True)),
                ('intro_title', models.CharField(blank=True, default=1, max_length=250, null=True)),
                ('intro_image', models.ImageField(upload_to='photos/home/%y/%m/%d')),
                ('intro_text', models.TextField()),
                ('about_us_title', models.CharField(blank=True, default=1, max_length=250, null=True)),
                ('about_us_image', models.ImageField(upload_to='photos/home/%y/%m/%d')),
                ('about_us_text', models.TextField()),
                ('before_after_title', models.CharField(blank=True, default=1, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
    ]
