# Generated by Django 3.1.12 on 2021-07-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210703_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'AboutUs', 'verbose_name_plural': 'AboutUs'},
        ),
        migrations.AlterModelOptions(
            name='beforeandafter',
            options={'verbose_name': 'BeforeAndAfter', 'verbose_name_plural': 'BeforeAndAfter'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Home'},
        ),
    ]
