# Generated by Django 3.1.12 on 2021-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210703_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforeandafter',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
