# Generated by Django 3.1.12 on 2021-07-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210703_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, default='https://www.facebook.com/', max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, default='https://www.instagram.com', max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, default='https://www.instagram.com', max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, default='https://twitter.com/', max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('first_phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('second_phone_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.AddField(
            model_name='home',
            name='FAQ',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='blog',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='about_us_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='intro_text',
            field=models.TextField(),
        ),
    ]
