# Generated by Django 3.1.12 on 2021-07-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='FAQ',
        ),
    ]
