# Generated by Django 3.1.12 on 2021-07-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_home_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='intro_title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
