# Generated by Django 3.1.12 on 2021-08-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_home_intro_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='intro_title',
            field=models.CharField(blank=True, default=1, max_length=250, null=True),
        ),
    ]
