# Generated by Django 3.1.12 on 2021-08-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210807_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='first_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='text_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/home/%y/%m/%d'),
        ),
    ]
