# Generated by Django 3.1.12 on 2021-08-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210812_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='first_text',
            new_name='type_question',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='about_us_title',
            field=models.CharField(blank=True, default=1, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='about_us_title',
            field=models.CharField(blank=True, default=1, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='before_after_title',
            field=models.CharField(blank=True, default=1, max_length=250, null=True),
        ),
    ]
