# Generated by Django 3.1.12 on 2021-08-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210822_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforeandafter',
            name='description',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
