# Generated by Django 3.1.12 on 2021-07-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_title', models.CharField(max_length=255)),
                ('answer', models.ImageField(upload_to='photos/answers/%y/%m/%d')),
                ('active', models.BooleanField(default=True)),
                ('hasCourse', models.BooleanField(default=False)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(default='000 0000 0000', max_length=15)),
                ('length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_answer', models.ImageField(upload_to='photos/client_answers/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], max_length=50)),
                ('question_title', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=400)),
                ('active', models.BooleanField(default=True)),
                ('hasDescription', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAnswerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.client')),
                ('client_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.clientanswer')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
            ],
            options={
                'unique_together': {('question', 'answer')},
            },
        ),
    ]
