# Generated by Django 3.1.12 on 2021-07-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/%y/%m/%d')),
            ],
            options={
                'verbose_name': 'LastPage',
                'verbose_name_plural': 'LastPage',
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answer'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='clientanswer',
            options={'verbose_name': 'ClientAnswer', 'verbose_name_plural': 'ClientAnswer'},
        ),
        migrations.AlterModelOptions(
            name='clientanswerlist',
            options={'verbose_name': 'ClientAnswerList', 'verbose_name_plural': 'ClientAnswerList'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionanswerlist',
            options={'verbose_name': 'QuestionAnswerList', 'verbose_name_plural': 'QuestionAnswerList'},
        ),
    ]
