# Generated by Django 3.1.12 on 2021-07-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210703_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastpage',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
