# Generated by Django 3.1.12 on 2021-07-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_lastpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastpage',
            name='whatsapp_button',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
