# Generated by Django 3.1.12 on 2021-07-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_lastpage_whatsapp_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastpage',
            name='whatsapp_button',
        ),
        migrations.AddField(
            model_name='lastpage',
            name='whatsapp_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
