# Generated by Django 3.1.12 on 2021-07-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210712_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientanswer',
            name='client_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.answer'),
        ),
    ]
