# Generated by Django 3.1.12 on 2021-07-13 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20210712_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientanswerlist',
            name='client_answer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='survey.answer'),
        ),
        migrations.DeleteModel(
            name='ClientAnswer',
        ),
    ]
