# Generated by Django 3.1.12 on 2021-07-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20210726_1808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientanswerlist',
            unique_together=set(),
        ),
    ]
