# Generated by Django 3.1.12 on 2021-08-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_client_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='length',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=models.CharField(max_length=15),
        ),
    ]
