# Generated by Django 3.1.12 on 2021-08-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20210807_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastpage',
            name='whatsapp_text',
            field=models.CharField(default='تواصل واتساب لبدء المتابعه', max_length=250),
        ),
    ]
